spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_system?useSSL=false
    username: postgres
    password: 66542
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  logginig:
    logging.file: ${user.home}/Pasys.log

#  messages:
#    basename: classpath:i18n/messages
#    encoding: UTF-8
#    fallback-to-system-locale: true
#    use-code-as-default-message: true
#    cache-duration: -1
#  thymeleaf:
#    prefix: classpath:templates/
#    suffix: .html
#    encoding: UTF-8
