--INSERT INTO customer(firstname,lastname)VALUES('ddeng','lololo');
--INSERT INTO customer(firstname,lastname)VALUES('yflow','dpdpdpd');
--INSERT INTO customer(firstname,lastname)VALUES('zilap','tototot');